about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AuthorView.as_view(), name='author'),
    path('tech/', views.TechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'),
    path(
        'group/<slug:slug>/',
        views.group_list,
        name='group_list'),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'),
    path(
        'create/',
        views.post_create,
        name='post_create'),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'),
    path(
        'posts/<int:post_id>/comment',
        views.add_comment,
        name='add_comment'),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'),
]

yatube_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from yatube_project import settings

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.TextField(max_length=100)
    slug = models.SlugField()
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.slug


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts')
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True)
    image = models.ImageField(
        'Image',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:20]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=[
                    'user',
                    'author'],
                name='unique follow')]

    def __str__(self):
        return f'user -{self.user}- follow to author -{self.author}-'

posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from posts.models import Post, Group, Comment

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'description', 'slug')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404


from posts.forms import PostForm, CommentForm
from posts.models import Post, Group, Comment, Follow

User = get_user_model()


def index(request):
    post_list = Post.objects.order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(posts_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    following = True
    posts_list = Post.objects.filter(author__username=username)
    paginator = Paginator(posts_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    profile = get_object_or_404(User, username=username)
    if not len(Follow.objects.filter(user=request.user, author=profile)):
        following = False
    context = {
        'profile': profile,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = get_list_or_404(Comment, post__pk=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    print(post.author.posts.count())
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    profile = get_object_or_404(User, username=request.user)
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = profile
        post.save()
        return redirect('posts:index')
    form = PostForm()
    context = {
        'form': form,
        'is_edit': False,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    profile = post.author.username
    if request.user.username == profile:
        form = PostForm(request.POST or None,
                        files=request.FILES or None,
                        instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
        context = {
            'form': form,
            'is_edit': True,
            'post_id': post_id,
        }
        return render(request, 'posts/create_post.html', context)
    return redirect('posts:profile', username=profile)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


@login_required
def profile_follow(request, username):
    user = get_object_or_404(User, username=request.user)
    author = get_object_or_404(User, username=username)
    Follow.objects.create(user=user, author=author)
    return redirect('posts:index')


@login_required
def profile_unfollow(request, username):
    follow_record = get_object_or_404(
        Follow,
        user__username=request.user,
        author__username=username)
    follow_record.delete()
    return redirect('about:tech')

templates/posts/comment.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h6 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h6>
      <p style="font-size: 70%">
         {{ comment.created }}
        </p>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}

templates/posts/create_post.html
{% extends 'base.html' %}
{% block tittle %} New Post {% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %} Редактирование поста {% else %} Новый пост {% endif %}
              </div>
              <div class="card-body">
                {% load user_filters %}

                {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}
                {% if is_edit %}
                  <form method="post" action="{% url 'posts:post_edit' post_id=post_id %}" enctype="multipart/form-data">
                {% else %}
                  <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
                {% endif %}
                  {% csrf_token %}
                  {% for field in form %}
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}

                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %} Отредактировать {% else %} Сохранить {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} HomePage {% endblock %}
{% block content %}
  <h1> It is homepage {{ name }}</h1>
  {% for post in page_obj %}
    <div class="col-12">
    <ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <li>
        Автор: <a href="{% url 'posts:profile' username=post.author.username %}"> {{ post.author }} </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group %}
      <a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы: {{ post.group.slug }}</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    </div>
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ group }} {% endblock %}
{% block content %}
  <h1> Records of group {{ group }} </h1>

  <p>list of last ten posts</p>
  <br>
  {% for post in page_obj %}
    <ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <li>
        Автор: <a href="{% url 'posts:profile' username=post.author.username %}"> {{ post.author }} </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} HomePage {% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <h1> It is homepage {{ name }}</h1>
  {% for post in page_obj %}
    <div class="col-12">
    <ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <li>
        Автор: <a href="{% url 'posts:profile' username=post.author.username %}"> {{ post.author }} </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group %}
      <a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы: {{ post.group.slug }}</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    </div>
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ post }} {% endblock %}
{% block content %}
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Автор: {{ post.author }}
            </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">Все посты автора</a>
              </li>
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
             Всего постов автора: {{ post.author.posts.count }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
             Подписчиков: XXX
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Подписок: XXX
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% include 'posts/comment.html' %}
        </article>
      </div>
    </div>
{% endblock %}

templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ username }} {% endblock %}
{% block content %}
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-2">
          <li class="list-group-item"> Профайл пользователя {{ profile.username }} </li>
          <li class="list-group-item"> Всего постов: {{ profile.posts.count }} </li>
          {% if post.group %}
            <a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы: {{ post.group.slug }}</a>
          {% endif %}
          {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' profile.username %}" role="button"
          >
            Отписаться
          </a>
          {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' profile.username %}" role="button"
            >
            Подписаться
          </a>
          {% endif %}
        </aside>
        <article class="col-12 col-md-10">
        {% for post in page_obj %}

          <ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p> {{ post.text }} </p>


        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
         </article>
      </div>
    </div>

{% include 'posts/includes/paginator.html' %}
{% endblock %}